services:
  dashboard:
    # image: localhost/deposit-dashboard
    image: docker.io/maven:3.9.9-eclipse-temurin-17
    command: sleep infinity
    container_name: dashboard
    hostname: dashboard
    restart: always
    ports:
      - "1901:1901"
    env_file:
      - .env
    volumes:
      - /exlibris/dps/nlnz_tools/dashboard:/exlibris/dps/nlnz_tools/dashboard
      - /mnt/d/data:/mnt/d/data
      - ./:/deposit-dashboard
