services:
  dashboard:
    image: localhost/deposit-dashboard:${app_version}
    command: --spring.config.additional-location=file:${PERSIST_PATH}/conf/
    container_name: dashboard
    hostname: dashboard
    restart: always
    ports:
      - "1901:1901"
    environment:
      - PERSIST_PATH=${PERSIST_PATH:-/exlibris/dps/nlnz_tools/dashboard}
    volumes:
      - /exlibris/dps/nlnz_tools/dashboard:/exlibris/dps/nlnz_tools/dashboard


