services:
  dashboard:
    image: localhost/deposit-dashboard
    container_name: dashboard
    hostname: dashboard
    restart: always
    ports:
      - "1901:1901"
    volumes:
      - /exlibris/dps/nlnz_tools/dashboard:/exlibris/dps/nlnz_tools/dashboard
      - /mnt/d/data:/mnt/d/data
